from enum import Enum


class UpgradeTypeEnum(Enum):
    MAX_HP_UP = "MAX_HP_UP"
    UNLOCK_SHIELD = "UNLOCK_SHIELD"
    SHIELD_CAPACITY_UP = "SHIELD_CAPACITY_UP"
    BULLET_DAMAGE_UP = "BULLET_DAMAGE_UP"
    DAMAGE_REDUCTION = "DAMAGE_REDUCTION"
    COIN_GAIN_UP = "COIN_GAIN_UP"
    ENEMY_SPEED_DOWN = "ENEMY_SPEED_DOWN"
    SPAWN_INTERVAL_UP = "SPAWN_INTERVAL_UP"